-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 22:45:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STUDENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COURSE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OFFICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OFFICE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OFFICE` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TEACHER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TEACHER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TEACHER` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `office_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_office_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`OFFICE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLASSROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLASSROOM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLASSROOM` (
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  INDEX `fk_course_id_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  PRIMARY KEY (`student_id`, `course_id`, `teacher_id`),
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`STUDENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`COURSE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`TEACHER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
